// Fixed public-role expectations; no numerical oracle is generated by the implementation.
import assert from "node:assert/strict";
import fs from "node:fs";
import canonicalize from "canonicalize";
import crypto from "node:crypto";
import Ajv2020 from "ajv/dist/2020.js";
import { verify, IDS } from "./envelope.mjs";
import { publishReceipt, validatePublic } from "./public.mjs";
import { artifact } from "./test-artifacts.mjs";
const load = (n) => JSON.parse(fs.readFileSync(new URL(n, import.meta.url)));
const record = load("example-record.jcs");
const expected = load("example-expected.json");
const rows = [];
const now = () => "2026-09-12T00:00:00.000Z";
function seal(r) {
  const { integrity, ...body } = r;
  integrity.content_digest =
    "sha256:" +
    crypto
      .createHash("sha256")
      .update("nomue/record-content/v1\n")
      .update(canonicalize(body))
      .digest("hex");
  return Buffer.from(canonicalize(r));
}
async function run(r, e, options = {}) {
  const raw = seal(r);
  const internal = await verify(JSON.stringify(e), raw, { now, ...options });
  const result = await publishReceipt(
    {
      category: "completed_valid",
      causes: {},
      result: {
        output: internal.output,
        ...(internal.verified_bytes
          ? { verified_record_base64: internal.verified_bytes.toString("base64") }
          : {}),
      },
    },
    { now },
  );
  assert.ok(await validatePublic(result.output));
  return { ...result, raw };
}
const good = await run(structuredClone(record), expected);
assert.deepEqual(good.output.conformance.schema, {
  schema_id: IDS.record,
  execution: "completed",
  outcome: "pass",
});
assert.deepEqual(
  good.output.conformance.checks.map((c) => c.stage),
  ["declaration", "admission"],
);
assert.deepEqual(
  good.output.verification_results.map((c) => c.stage),
  ["integrity", "context", "arithmetic"],
);
assert.equal(good.output.checks, undefined);
assert.equal(good.verified_record_base64, good.raw.toString("base64"));
rows.push({ name: "structural and semantic conformance separated from verification" });
const wrongContext = structuredClone(expected);
wrongContext.record_id = "urn:other:record";
const context = await run(structuredClone(record), wrongContext);
assert.equal(context.output.verification_results[1].outcome, "fail");
assert.ok(
  context.output.conformance.checks.every(
    (c) => c.execution === "not_run" && !Object.hasOwn(c, "outcome"),
  ),
);
assert.equal(context.output.verification_results[2].execution, "not_run");
assert.equal(context.verified_record_base64, undefined);
rows.push({ name: "context failure never manufactures semantic conformance" });
const relationRecord = structuredClone(record);
relationRecord.payload.declaration.dataset.observations[0].experimental_unit_id = "missing-unit";
const relationExpected = structuredClone(expected);
relationExpected.declaration = structuredClone(relationRecord.payload.declaration);
const relation = await run(relationRecord, relationExpected);
assert.equal(relation.output.conformance.checks[0].outcome, "fail");
assert.deepEqual(relation.output.conformance.checks[0].reason_codes, [
  "candidate:holm:declaration_invalid",
]);
assert.equal(relation.output.conformance.checks[1].execution, "not_run");
assert.equal(relation.output.verification_results[2].execution, "not_run");
assert.equal(relation.verified_record_base64, undefined);
rows.push({ name: "relation failure belongs to conformance and gates arithmetic" });
const mismatchRecord = structuredClone(record);
mismatchRecord.payload.result.adjusted.at(-1).adjusted_hex = "0";
const mismatch = await run(mismatchRecord, expected);
assert.ok(mismatch.output.conformance.checks.every((c) => c.outcome === "pass"));
assert.equal(mismatch.output.verification_results[2].outcome, "fail");
assert.equal(mismatch.verified_record_base64, undefined);
rows.push({ name: "arithmetic disagreement does not invert conformance" });
const error = await run(structuredClone(record), expected, {
  runner: async () => {
    throw Error("fixed worker failure");
  },
});
assert.equal(error.output.verification_results[2].execution, "error");
assert.equal(error.output.verification_results[2].outcome, undefined);
rows.push({ name: "worker error remains distinct from disagreement" });
const schema = new Ajv2020({ strict: false }).compile(load("report.schema.json"));
const mutations = [
  [
    "merged checks",
    (r) => {
      r.checks = [...r.conformance.checks, ...r.verification_results];
    },
  ],
  [
    "swapped roles",
    (r) => {
      [r.conformance.checks[0], r.verification_results[0]] = [
        r.verification_results[0],
        r.conformance.checks[0],
      ];
    },
  ],
  [
    "missing conformance",
    (r) => {
      delete r.conformance;
    },
  ],
  [
    "missing semantic row",
    (r) => {
      r.conformance.checks.pop();
    },
  ],
  [
    "wrong structural schema",
    (r) => {
      r.conformance.schema.schema_id = IDS.expected;
    },
  ],
  [
    "invented structural failure in report",
    (r) => {
      r.conformance.schema.outcome = "fail";
    },
  ],
  [
    "aggregate conformance claim",
    (r) => {
      r.conformance.overall_status = "pass";
    },
  ],
  [
    "erased semantic failure",
    (r) => {
      r.conformance.checks[0].outcome = "pass";
      r.conformance.checks[0].reason_codes = [];
    },
  ],
];
for (const [name, mutate] of mutations) {
  const r = structuredClone(name === "erased semantic failure" ? relation.output : good.output);
  mutate(r);
  // Role/shape corruption is schema-rejected; manufactured success is gating-rejected.
  if (name !== "erased semantic failure") assert.equal(schema(r), false, name);
  assert.equal(await validatePublic(r), false, name);
  rows.push({ name: "reject " + name });
}
const invalid = structuredClone(record);
delete invalid.payload.contract_id;
const refused = await run(invalid, expected);
assert.equal(refused.output.output_type, "nomue-verifier-refusal");
for (const k of ["conformance", "verification_results", "checks"])
  assert.equal(refused.output[k], undefined);
assert.equal(refused.verified_record_base64, undefined);
rows.push({ name: "schema failure produces refusal without conformance or verification" });
await artifact("SEPARATION-RESULTS.json", {
  status: "author-context controls; no independent approval",
  controls: rows.length,
  rows,
});
console.log(`${rows.length} conformance separation controls passed`);
