#!/usr/bin/env python3
"""Deterministic reproductions for the SR-D primary-source investigation.

Scope: closed testing (Marcus, Peritz and Gabriel 1976), the fallback procedure
(Wiens 2003), parallel and serial Bonferroni gatekeeping (Dmitrienko, Offen and
Westfall 2003) and the graphical approach (Bretz, Maurer, Brannath and Posch
2009).  Every check is exact rational arithmetic or a closed-form numerical
computation; there is no random number generation and no simulation.

The script needs only the Python standard library.  Run:

    python3 review-inputs/r3-srd-primary-investigation/reproduce-sr-d.py

It exits with status 0 when every recorded expectation is met and prints one
line per check.  Expected values are transcribed from the printed originals and
are cited by printed page in REVIEW-RESULT.md; they are not generated by this
script.
"""

from __future__ import annotations

import itertools
import math
from fractions import Fraction as F

FAILURES: list[str] = []


def check(name: str, ok: bool, detail: str = "") -> None:
    status = "ok  " if ok else "FAIL"
    print(f"[{status}] {name}" + (f"  ({detail})" if detail else ""))
    if not ok:
        FAILURES.append(name)


# --------------------------------------------------------------------------
# 1. Generic closed testing with weighted Bonferroni / weighted Simes tests
# --------------------------------------------------------------------------


def subsets(m: int):
    """All non-empty index subsets of {0, ..., m-1} as frozensets."""
    for r in range(1, m + 1):
        for c in itertools.combinations(range(m), r):
            yield frozenset(c)


def bonferroni_p(H, p, v):
    """Weighted Bonferroni p-value min_i p_i / v_i(H); v_i = 0 contributes 1."""
    vals = [p[i] / v[i] if v[i] > 0 else F(1) for i in H]
    return min(min(vals), F(1))


def simes_p(H, p, v, normalise=False):
    """Weighted Simes p-value min_l p_(l) / sum_{i<=l} v_(i) (Dmitrienko p. 2393).

    With normalise=True the weights are first rescaled to sum to one over H
    (the Benjamini-Hochberg 1997 form); the printed formula does not rescale.
    """
    order = sorted(H, key=lambda i: p[i])
    total = sum(v[i] for i in H)
    best = F(1)
    cum = F(0)
    for i in order:
        cum += v[i] / total if (normalise and total > 0) else v[i]
        if cum > 0:
            best = min(best, p[i] / cum)
    return best


def simes_p_normalised(H, p, v):
    return simes_p(H, p, v, normalise=True)


def singleton_full_level(weight_fn):
    """Table II convention (printed p. 2394): a singleton gatekeeper intersection uses p_i itself."""

    def fn(H):
        v = weight_fn(H)
        if len(H) == 1:
            (i,) = tuple(H)
            v = [F(0)] * len(v)
            v[i] = F(1)
        return v

    return fn


def closed_adjusted(m, p, weight_fn, local=bonferroni_p):
    """Adjusted p-values max over intersections containing H_i (Dmitrienko p. 2389)."""
    adj = [F(0)] * m
    for H in subsets(m):
        v = weight_fn(H)
        assert all(v[i] == 0 for i in range(m) if i not in H)
        assert sum(v) <= 1
        pH = local(H, p, v)
        for i in H:
            adj[i] = max(adj[i], pH)
    return adj


# --------------------------------------------------------------------------
# 2. Dmitrienko, Offen and Westfall (2003) weighting algorithms
# --------------------------------------------------------------------------


def dow_parallel_weights(k, m, w):
    """Algorithm 1 (printed p. 2390): parallel Bonferroni gatekeeping weights."""
    gate = set(range(k))

    def fn(H):
        v = [F(0)] * m
        gates_in = [i for i in H if i in gate]
        secs_in = [i for i in H if i not in gate]
        if len(gates_in) == k:  # Case 1
            for i in gates_in:
                v[i] = w[i]
        elif gates_in:  # Case 2
            rem = 1 - sum(w[i] for i in gates_in)
            den = sum(w[i] for i in secs_in)
            for i in gates_in:
                v[i] = w[i]
            for i in secs_in:
                v[i] = w[i] * rem / den
        else:  # Case 3
            den = sum(w[i] for i in secs_in)
            for i in secs_in:
                v[i] = w[i] / den
        return v

    return fn


def dow_serial_weights(k, m, w):
    """Algorithm 2 (printed p. 2391): serial Bonferroni gatekeeping weights."""
    gate = set(range(k))

    def fn(H):
        v = [F(0)] * m
        gates_in = [i for i in H if i in gate]
        secs_in = [i for i in H if i not in gate]
        if gates_in:  # Case 1
            den = sum(w[i] for i in gates_in)
            for i in gates_in:
                v[i] = w[i] / den
        else:  # Case 2
            den = sum(w[i] for i in secs_in)
            for i in secs_in:
                v[i] = w[i] / den
        return v

    return fn


# --------------------------------------------------------------------------
# 3. Bretz, Maurer, Brannath and Posch (2009) graph algorithms
# --------------------------------------------------------------------------


def remove_vertex(alpha, G, I, j):
    """One application of (A3)/(A4) = Step 3 of Algorithm 1 (printed pp. 591, 602-603)."""
    I2 = I - {j}
    a2 = {l: alpha[l] + alpha[j] * G[j][l] for l in I2}
    G2 = {l: {} for l in I2}
    for l in I2:
        for kk in I2:
            if l == kk:
                G2[l][kk] = F(0)
            else:
                den = 1 - G[l][j] * G[j][l]
                G2[l][kk] = (G[l][kk] + G[l][j] * G[j][kk]) / den if den != 0 else F(0)
    return a2, G2


def graph_weights(alpha, G, m, I):
    """Local levels for intersection I by removing vertices outside I (Remark (v))."""
    a = dict(alpha)
    g = {l: dict(G[l]) for l in G}
    cur = frozenset(range(m))
    for j in sorted(set(range(m)) - set(I)):
        a, g = remove_vertex(a, g, cur, j)
        cur = cur - {j}
    return a


def graph_algorithm1(alpha, G, p, m):
    """Algorithm 1 (printed p. 591): sequentially rejective shortcut."""
    I = frozenset(range(m))
    a = dict(alpha)
    g = {l: dict(G[l]) for l in G}
    rejected = []
    while I:
        cand = [i for i in I if a[i] > 0 and p[i] <= a[i]]
        if not cand:
            break
        j = min(I, key=lambda i: (p[i] / a[i]) if a[i] > 0 else F(10**9))
        if not (a[j] > 0 and p[j] <= a[j]):
            break
        rejected.append(j)
        a, g = remove_vertex(a, g, I, j)
        I = I - {j}
    return frozenset(rejected)


def graph_algorithm2(alpha, G, p, m, alpha_total):
    """Algorithm 2 (printed p. 595): adjusted p-values."""
    I = frozenset(range(m))
    w = {i: alpha[i] / alpha_total for i in range(m)}
    g = {l: dict(G[l]) for l in G}
    pmax = F(0)
    adj = {}
    while I:
        j = min(I, key=lambda i: (p[i] / w[i]) if w[i] > 0 else F(10**9))
        pj = p[j] / w[j] if w[j] > 0 else F(1)
        adj[j] = min(max(pj, pmax), F(1))
        pmax = adj[j]
        w, g = remove_vertex(w, g, I, j)
        I = I - {j}
    return adj


def closed_rejections_from_graph(alpha, G, m, p, alpha_total):
    """Full closure with weighted Bonferroni tests whose weights come from the graph."""
    rej = set()
    for i in range(m):
        ok = True
        for H in subsets(m):
            if i not in H:
                continue
            a = graph_weights(alpha, G, m, H)
            if not any(a[l] > 0 and p[l] <= a[l] for l in H):
                ok = False
                break
        if ok:
            rej.add(i)
    return frozenset(rej)


def chain_graph(m, eps=F(0)):
    G = {i: {j: F(0) for j in range(m)} for i in range(m)}
    for i in range(m - 1):
        G[i][i + 1] = F(1)
    return G


# --------------------------------------------------------------------------
# 4. Wiens (2003) fallback and the fixed-sequence special case
# --------------------------------------------------------------------------


def wiens_fallback(alpha_prime, p):
    """Section 2.3 (printed p. 213): sequential rule with accumulation."""
    rejected = []
    prev_level = F(0)
    prev_rejected = False
    for i, (a, pi) in enumerate(zip(alpha_prime, p)):
        level = a + prev_level if prev_rejected else a
        if level > 0 and pi <= level:
            rejected.append(i)
            prev_rejected = True
        else:
            prev_rejected = False
        prev_level = level
    return frozenset(rejected)


# --------------------------------------------------------------------------
# 5. Marcus, Peritz and Gabriel (1976): PAVA, D^2 statistics, null distribution
# --------------------------------------------------------------------------


def pava(x, n=None):
    """Isotonic (non-decreasing) weighted least squares by pool-adjacent-violators."""
    n = n or [1] * len(x)
    blocks = [[F(v), F(w), 1] for v, w in zip(x, n)]  # value, weight, count
    i = 0
    while i < len(blocks) - 1:
        if blocks[i][0] > blocks[i + 1][0]:
            v = (blocks[i][0] * blocks[i][1] + blocks[i + 1][0] * blocks[i + 1][1]) / (
                blocks[i][1] + blocks[i + 1][1]
            )
            blocks[i] = [v, blocks[i][1] + blocks[i + 1][1], blocks[i][2] + blocks[i + 1][2]]
            del blocks[i + 1]
            i = max(i - 1, 0)
        else:
            i += 1
    out = []
    for v, _w, c in blocks:
        out.extend([v] * c)
    return out


def d2_statistic(xbar, partition):
    """D_g^2 of printed p. 657 with n_i = 1 and sigma^2 = 1."""
    total = F(0)
    for block in partition:
        vals = [F(xbar[i - 1]) for i in block]
        mean = sum(vals) / len(vals)
        fit = pava(vals)
        total += sum((f - mean) ** 2 for f in fit)
    return total


def stirling1_unsigned(n):
    """|s(n, m)| for m = 0..n."""
    row = [1]
    for i in range(n):
        new = [0] * (len(row) + 1)
        for m_, c in enumerate(row):
            new[m_] += i * c
            new[m_ + 1] += c
        row = new
    return row


def level_probabilities(lam):
    """p(m; lambda) for equal sample sizes: |s(lambda, m)| / lambda!."""
    s = stirling1_unsigned(lam)
    return {m_: F(s[m_], math.factorial(lam)) for m_ in range(1, lam + 1)}


def chi2_sf(df, x):
    """Upper tail of chi-square with integer df (closed forms; df = 0 gives 0)."""
    if df == 0:
        return 0.0
    if x <= 0:
        return 1.0
    if df % 2 == 0:
        n = df // 2
        term = 1.0
        total = 0.0
        for i in range(n):
            if i > 0:
                term *= (x / 2) / i
            total += term
        return math.exp(-x / 2) * total
    n = (df - 1) // 2
    total = math.erfc(math.sqrt(x / 2))
    coeff = math.sqrt(2 * x / math.pi) * math.exp(-x / 2)
    term = 1.0  # x^(i-1) / (1 * 3 * ... * (2i-1)) for i = 1, ..., n
    for i in range(1, n + 1):
        if i > 1:
            term *= x / (2 * i - 1)
        total += coeff * term
    return total


def dg2_sf(lams, t2):
    """pr(D_g^2 > t^2) from the equal-n formula on printed p. 658."""
    probs = [level_probabilities(lam) for lam in lams]
    total = 0.0
    for ms in itertools.product(*[range(1, lam + 1) for lam in lams]):
        prob = 1.0
        for pj, m_ in zip(probs, ms):
            prob *= float(pj[m_])
        df = sum(ms) - len(lams)
        total += prob * chi2_sf(df, t2)
    return total


def dg2_critical(lams, alpha):
    lo, hi = 0.0, 60.0
    for _ in range(200):
        mid = (lo + hi) / 2
        if dg2_sf(lams, mid) > alpha:
            lo = mid
        else:
            hi = mid
    return (lo + hi) / 2


def norm_quantile(q):
    lo, hi = -10.0, 10.0
    for _ in range(200):
        mid = (lo + hi) / 2
        if 0.5 * math.erfc(-mid / math.sqrt(2)) < q:
            lo = mid
        else:
            hi = mid
    return (lo + hi) / 2


# ==========================================================================
# Checks
# ==========================================================================


def main() -> int:
    print("SR-D reproductions (exact rational arithmetic unless stated)\n")

    # ---- Dmitrienko Table I (printed p. 2391): equal weights, k = 2, m = 4 ----
    w_eq = [F(1, 2), F(1, 2), F(1, 2), F(1, 2)]
    fn = dow_parallel_weights(2, 4, w_eq)
    table1 = {
        (0, 1, 2, 3): (F(1, 2), F(1, 2), 0, 0),
        (0, 1, 2): (F(1, 2), F(1, 2), 0, 0),
        (0, 1, 3): (F(1, 2), F(1, 2), 0, 0),
        (0, 1): (F(1, 2), F(1, 2), 0, 0),
        (0, 2, 3): (F(1, 2), 0, F(1, 4), F(1, 4)),
        (0, 2): (F(1, 2), 0, F(1, 2), 0),
        (0, 3): (F(1, 2), 0, 0, F(1, 2)),
        (0,): (F(1, 2), 0, 0, 0),
        (1, 2, 3): (0, F(1, 2), F(1, 4), F(1, 4)),
        (1, 2): (0, F(1, 2), F(1, 2), 0),
        (1, 3): (0, F(1, 2), 0, F(1, 2)),
        (1,): (0, F(1, 2), 0, 0),
        (2, 3): (0, 0, F(1, 2), F(1, 2)),
        (2,): (0, 0, 1, 0),
        (3,): (0, 0, 0, 1),
    }
    ok = all(tuple(fn(frozenset(H))) == tuple(F(x) for x in row) for H, row in table1.items())
    check("Dmitrienko Table I: Algorithm 1 reproduces all 15 weight rows", ok)

    # ---- Dmitrienko Table II / Table III (printed pp. 2394-2395) ----
    w = [F(9, 10), F(1, 10), F(1, 2), F(1, 2)]
    fn = dow_parallel_weights(2, 4, w)
    # Table II row check: H_1011 uses (p1/0.9, p3/0.05, p4/0.05); H_0111 uses (p2/0.1, p3/0.45, p4/0.45)
    v1011 = fn(frozenset({0, 2, 3}))
    v0111 = fn(frozenset({1, 2, 3}))
    check(
        "Dmitrienko Table II: weights of H_1011 and H_0111",
        v1011 == [F(9, 10), 0, F(1, 20), F(1, 20)] and v0111 == [0, F(1, 10), F(9, 20), F(9, 20)],
    )
    scenarios = {
        1: ([F(24, 1000), F(3, 1000), F(26, 1000), F(2, 1000)], [0.0267, 0.0300, 0.0289, 0.0267], [0.0260, 0.0260, 0.0260, 0.0253]),
        2: ([F(84, 1000), F(3, 1000), F(26, 1000), F(2, 1000)], [0.0933, 0.0300, 0.0933, 0.0400], [0.0840, 0.0300, 0.0840, 0.0400]),
        3: ([F(48, 1000), F(3, 1000), F(26, 1000), F(2, 1000)], [0.0533, 0.0300, 0.0533, 0.0400], [0.0480, 0.0300, 0.0480, 0.0400]),
    }
    fn_tab2 = singleton_full_level(fn)
    for s, (p, exp_b, exp_s) in scenarios.items():
        adj_b = closed_adjusted(4, p, fn, bonferroni_p)
        adj_s_raw = closed_adjusted(4, p, fn, simes_p)
        adj_s_norm = closed_adjusted(4, p, fn, simes_p_normalised)
        adj_s_tab2 = closed_adjusted(4, p, fn_tab2, simes_p)
        adj_b_tab2 = closed_adjusted(4, p, fn_tab2, bonferroni_p)
        got_b = [round(float(x), 4) for x in adj_b]
        got_s_raw = [round(float(x), 4) for x in adj_s_raw]
        got_s_norm = [round(float(x), 4) for x in adj_s_norm]
        got_s_tab2 = [round(float(x), 4) for x in adj_s_tab2]
        got_b_tab2 = [round(float(x), 4) for x in adj_b_tab2]
        check(f"Dmitrienko Table III scenario {s}: Bonferroni column = Algorithm 1 / Table I weights (singleton gatekeeper at w_i)", got_b == exp_b, f"{got_b}")
        check(f"Dmitrienko Table III scenario {s}: Simes column = weights rescaled to sum 1 within H (singleton at level alpha)", got_s_norm == exp_s, f"{got_s_norm}")
        check(f"Dmitrienko Table III scenario {s}: Simes column also = printed formula with Table II singleton convention", got_s_tab2 == exp_s, f"{got_s_tab2}")
        check(f"Dmitrienko Table III scenario {s}: printed Simes formula with unrescaled Algorithm 1 weights does NOT give the printed column", got_s_raw != exp_s, f"{got_s_raw}")
        if s == 1:
            check("Dmitrienko Table III scenario 1: Bonferroni with the Table II singleton convention gives 0.0289 for mortality, not the printed 0.0300", got_b_tab2 == [0.0267, 0.0289, 0.0289, 0.0267], f"{got_b_tab2}")
        else:
            check(f"Dmitrienko Table III scenario {s}: the singleton convention does not change the Bonferroni column here", got_b_tab2 == exp_b, f"{got_b_tab2}")
        # gatekeeper adjusted p equals p_i / w_i (printed p. 2392) under the Table I convention
        check(f"Dmitrienko scenario {s}: gatekeeper adjusted p = p_i/w_i (Table I convention)", adj_b[0] == p[0] / w[0] and adj_b[1] == p[1] / w[1])
        # condition 2 (printed p. 2390): secondary adjusted p >= min gatekeeper adjusted p
        check(f"Dmitrienko scenario {s}: condition 2 holds (>= form)", min(adj_b[2], adj_b[3]) >= min(adj_b[0], adj_b[1]))
    # Under the Table II convention the stated property adjusted p_i = p_i / w_i (p. 2392) can fail
    p_ce = [F(24, 1000), F(1, 1000), F(1, 1000), F(1, 1000)]
    adj_ce = closed_adjusted(4, p_ce, fn_tab2, bonferroni_p)
    check("Investigator: with singleton gatekeeper at level alpha, adjusted p_1 = p_1 < p_1/w_1 for p = (0.024, 0.001, 0.001, 0.001)", adj_ce[0] == p_ce[0] and adj_ce[0] < p_ce[0] / w[0], f"{float(adj_ce[0])} vs {float(p_ce[0]/w[0]):.4f}")
    # Algorithm 1 Case 2 for a gatekeeper-only proper subset: the secondary formula is vacuous and the weights sum to less than 1
    fn3 = dow_parallel_weights(3, 5, [F(1, 2), F(3, 10), F(1, 5), F(1, 2), F(1, 2)])
    v3 = fn3(frozenset({0, 1}))
    check("Dmitrienko Algorithm 1 Case 2 with no secondary in H (k=3, H = H1 and H2): weights (w1, w2, 0, 0, 0), sum 0.8 < 1", v3 == [F(1, 2), F(3, 10), 0, 0, 0])

    # ---- Serial gatekeeping (Algorithm 2): secondary adjusted p >= max gatekeeper adjusted p ----
    fn_serial = dow_serial_weights(2, 4, w)
    ok = True
    grid = [F(1, 1000), F(1, 100), F(3, 100), F(6, 100), F(2, 10)]
    for p in itertools.product(grid, repeat=4):
        adj = closed_adjusted(4, list(p), fn_serial)
        if min(adj[2], adj[3]) < max(adj[0], adj[1]):
            ok = False
            break
    check("Dmitrienko Algorithm 2: secondary adjusted p >= max gatekeeper adjusted p on a 625-point grid", ok)

    # ---- Bretz Figure 2 graph reproduces Dmitrienko Algorithm 1 weights ----
    def parallel_graph(k, m, w, alpha):
        alpha_v = {i: (w[i] * alpha if i < k else F(0)) for i in range(m)}
        G = {i: {j: F(0) for j in range(m)} for i in range(m)}
        for i in range(k):
            for j in range(k, m):
                G[i][j] = w[j]
        for i in range(k, m):
            for j in range(k, m):
                if i != j:
                    G[i][j] = w[j] / (1 - w[i])
        return alpha_v, G

    alpha = F(5, 100)
    for label, ww in (("equal weights", w_eq), ("weights (0.9, 0.1, 0.5, 0.5)", w)):
        a_v, G = parallel_graph(2, 4, ww, alpha)
        fn = dow_parallel_weights(2, 4, ww)
        ok = True
        for H in subsets(4):
            gw = graph_weights(a_v, G, 4, H)
            dw = fn(H)
            if any(gw[i] != dw[i] * alpha for i in H):
                ok = False
        check(f"Bretz Figure 2 graph = Dmitrienko Algorithm 1 weights for all 15 intersections ({label})", ok)

    # Generalisation (investigator derivation, not a source claim): k = 3, m = 6, unequal weights
    w6 = [F(1, 2), F(3, 10), F(1, 5), F(1, 10), F(3, 5), F(3, 10)]
    a_v, G = parallel_graph(3, 6, w6, alpha)
    fn = dow_parallel_weights(3, 6, w6)
    ok = True
    for H in subsets(6):
        gw = graph_weights(a_v, G, 6, H)
        dw = fn(H)
        if any(gw[i] != dw[i] * alpha for i in H):
            ok = False
    check("Investigator: proportional graph = Dmitrienko Algorithm 1 for k=3, m=6, unequal weights (63 intersections)", ok)

    # Order independence of vertex removal (Bretz Appendix (ii)) on the k=3, m=6 graph
    ok = True
    for H in [frozenset({0, 3}), frozenset({1, 4, 5}), frozenset({2})]:
        results = set()
        for order in itertools.permutations(sorted(set(range(6)) - H)):
            a = dict(a_v)
            g = {l: dict(G[l]) for l in G}
            cur = frozenset(range(6))
            for j in order:
                a, g = remove_vertex(a, g, cur, j)
                cur = cur - {j}
            results.add(tuple(sorted(a.items())))
        if len(results) != 1:
            ok = False
    check("Bretz Appendix (ii): removal order does not change the generated levels (three subsets, all orders)", ok)

    # ---- Bretz Figure 5 bottom graph: loop update (printed p. 592) ----
    a_v = {0: F(1), 1: F(2), 2: F(3)}  # symbolic stand-ins alpha1, alpha2, alpha3 as 1, 2, 3
    G = {0: {0: F(0), 1: F(1, 2), 2: F(1, 2)}, 1: {0: F(1, 2), 1: F(0), 2: F(1, 2)}, 2: {0: F(0), 1: F(0), 2: F(0)}}
    a2, G2 = remove_vertex(a_v, G, frozenset({0, 1, 2}), 1)
    check(
        "Bretz Figure 5 (bottom): after rejecting H2, levels (a1+a2/2, a3+a2/2) and g13 = 1",
        a2 == {0: F(1) + F(2, 2), 2: F(3) + F(2, 2)} and G2[0][2] == 1,
    )

    # ---- Bretz Figure 4 / Algorithm 2 example (printed pp. 590, 595) ----
    m = 3
    a_v = {i: F(5, 100) / 3 for i in range(3)}
    G = {i: {j: (F(1, 2) if i != j else F(0)) for j in range(3)} for i in range(3)}
    p = [F(2, 100), F(55, 1000), F(12, 1000)]
    rej = graph_algorithm1(a_v, G, p, 3)
    adj = graph_algorithm2(a_v, G, p, 3, F(5, 100))
    check("Bretz Figure 4: Holm graph rejects H3 then H1, not H2", rej == frozenset({0, 2}))
    check(
        "Bretz Algorithm 2 example: adjusted p = (0.04, 0.055, 0.036)",
        [round(float(adj[i]), 3) for i in range(3)] == [0.04, 0.055, 0.036],
        f"{[float(adj[i]) for i in range(3)]}",
    )
    check("Bretz Figure 4: closure with graph weights gives the same rejections", closed_rejections_from_graph(a_v, G, 3, p, F(5, 100)) == rej)

    # ---- Bretz Section 3.3 epsilon-graphs (printed pp. 596-598) ----
    eps = F(1, 10**9)

    def eps_levels(a):
        # drop O(eps) contributions when reading levels (calculation rule eps -> 0)
        return {i: F(round(float(v) * 10**8), 10**8) for i, v in a.items()}

    # Figure 9: Holm on H1, H2 as gatekeeper, H3 only if both rejected
    a_v = {0: F(5, 200), 1: F(5, 200), 2: F(0)}
    G = {0: {0: F(0), 1: F(1), 2: F(0)}, 1: {0: 1 - eps, 1: F(0), 2: eps}, 2: {0: F(0), 1: F(0), 2: F(0)}}
    p = [F(4, 100), F(1, 100), F(3, 100)]
    rej = graph_algorithm1(a_v, G, p, 3)
    check("Bretz Figure 9: p = (0.04, 0.01, 0.03) rejects all three hypotheses", rej == frozenset({0, 1, 2}))
    # after removing H2 the edge H1 -> H3 has weight 1 (eps/(1-(1-eps)))
    a2, G2 = remove_vertex(a_v, G, frozenset({0, 1, 2}), 1)
    check("Bretz Figure 9: after rejecting H2, edge H1 -> H3 has weight 1", G2[0][2] == 1)
    # Figure 10: r1 = 0.8, r2 = 0.2
    r1, r2 = F(8, 10), F(2, 10)
    a_v = {0: F(5, 200), 1: F(5, 200), 2: F(0), 3: F(0)}
    G = {
        0: {0: F(0), 1: F(1), 2: F(0), 3: F(0)},
        1: {0: 1 - eps, 1: F(0), 2: r1 * eps, 3: r2 * eps},
        2: {0: F(0), 1: F(0), 2: F(0), 3: F(1)},
        3: {0: F(0), 1: F(0), 2: F(1), 3: F(0)},
    }
    p = [F(4, 100), F(1, 100), F(3, 100), F(4, 100)]
    rej = graph_algorithm1(a_v, G, p, 4)
    a2, G2 = remove_vertex(a_v, G, frozenset({0, 1, 2, 3}), 1)
    a3, _ = remove_vertex(a2, G2, frozenset({0, 2, 3}), 0)
    check("Bretz Figure 10: all four hypotheses rejected; after H2 and H1 the levels of H3, H4 are 0.04 and 0.01", rej == frozenset({0, 1, 2, 3}) and eps_levels(a3) == {2: F(4, 100), 3: F(1, 100)})

    # Figure 2 (original) versus Figure 12 (improved) with p = (0.02, 0.04, 0.01, 0.015)
    a_v = {0: F(5, 200), 1: F(5, 200), 2: F(0), 3: F(0)}
    G_fig2 = {
        0: {0: F(0), 1: F(0), 2: F(1, 2), 3: F(1, 2)},
        1: {0: F(0), 1: F(0), 2: F(1, 2), 3: F(1, 2)},
        2: {0: F(0), 1: F(0), 2: F(0), 3: F(1)},
        3: {0: F(0), 1: F(0), 2: F(1), 3: F(0)},
    }
    G_fig12 = {
        0: {0: F(0), 1: F(0), 2: F(1, 2), 3: F(1, 2)},
        1: {0: F(0), 1: F(0), 2: F(1, 2), 3: F(1, 2)},
        2: {0: eps, 1: F(0), 2: F(0), 3: 1 - eps},
        3: {0: F(0), 1: eps, 2: 1 - eps, 3: F(0)},
    }
    p = [F(2, 100), F(4, 100), F(1, 100), F(15, 1000)]
    rej2 = graph_algorithm1(a_v, G_fig2, p, 4)
    rej12 = graph_algorithm1(a_v, G_fig12, p, 4)
    check("Bretz p. 598 example: Figure 2 procedure rejects exactly H1, H3, H4 (printed text says H1, H2, H3)", rej2 == frozenset({0, 2, 3}))
    check("Bretz p. 598 example: Figure 12 procedure rejects all four", rej12 == frozenset({0, 1, 2, 3}))

    # ---- Serial gatekeeping as an epsilon-graph reproduces Dmitrienko Algorithm 2 (investigator derivation) ----
    k, m = 2, 4
    ww = w
    a_v = {i: (ww[i] * alpha if i < k else F(0)) for i in range(m)}
    G = {i: {j: F(0) for j in range(m)} for i in range(m)}
    for i in range(k):
        for j in range(k):
            if i != j:
                G[i][j] = (ww[j] / (1 - ww[i])) * (1 - eps)
        for j in range(k, m):
            G[i][j] = ww[j] * eps
    for i in range(k, m):
        for j in range(k, m):
            if i != j:
                G[i][j] = ww[j] / (1 - ww[i])
    fn_serial = dow_serial_weights(k, m, ww)
    ok = True
    for H in subsets(m):
        gw = eps_levels(graph_weights(a_v, G, m, H))
        dw = fn_serial(H)
        if any(gw[i] != dw[i] * alpha for i in H):
            ok = False
    check("Investigator: epsilon-graph of Bretz Section 3.3 = Dmitrienko Algorithm 2 (serial) weights, k=2, m=4", ok)

    # ---- Wiens fallback = Bretz chain graph with a = (a1, a2, a3); fixed sequence = (alpha, 0, 0) ----
    alpha_prime = [F(3, 100), F(15, 1000), F(5, 1000)]
    grid = [F(1, 1000), F(4, 1000), F(6, 1000), F(1, 100), F(2, 100), F(3, 100), F(4, 100), F(45, 1000), F(6, 100), F(2, 10)]
    G = chain_graph(3)
    a_v = {i: alpha_prime[i] for i in range(3)}
    ok_seq = ok_closure = True
    for p in itertools.product(grid, repeat=3):
        rw = wiens_fallback(alpha_prime, list(p))
        rg = graph_algorithm1(a_v, G, list(p), 3)
        if rw != rg:
            ok_seq = False
        if closed_rejections_from_graph(a_v, G, 3, list(p), F(5, 100)) != rw:
            ok_closure = False
    check("Wiens fallback rule = Bretz chain-graph Algorithm 1 on a 1000-point grid (m = 3, unequal alpha')", ok_seq)
    check("Wiens fallback rule = full weighted-Bonferroni closure with chain-graph weights (same grid)", ok_closure)
    a_fs = {0: F(5, 100), 1: F(0), 2: F(0)}
    ok = True
    for p in itertools.product(grid, repeat=3):
        if wiens_fallback([F(5, 100), F(0), F(0)], list(p)) != graph_algorithm1(a_fs, G, list(p), 3):
            ok = False
    check("Fixed sequence = fallback with a = (alpha, 0, 0) = Bretz Figure 6 graph (same grid)", ok)

    # Exact worst-case FWER of the fallback under independent uniform null p-values (investigator derivation)
    a1, a2, a3 = alpha_prime
    worst = {
        "TTT": a1 + (1 - a1) * a2 + (1 - a1) * (1 - a2) * a3,
        "FTT": (a1 + a2) + (1 - a1 - a2) * a3,
        "TFT": a1 + (1 - a1) * (a2 + a3),
        "TTF": a1 + (1 - a1) * a2,
        "FFT": a1 + a2 + a3,
        "FTF": a1 + a2,
        "TFF": a1,
    }
    check(
        "Investigator: fallback FWER <= alpha for every true/false configuration (independent uniforms, false p = 0)",
        all(v <= F(5, 100) for v in worst.values()),
        ", ".join(f"{k_}={float(v):.4f}" for k_, v in worst.items()),
    )

    # Wiens p. 213 efficiency remark (illustrative, not decision-bearing): sample-size ratios at 80% power
    z80 = norm_quantile(0.8)
    base = (norm_quantile(0.975) + z80) ** 2
    r01 = (norm_quantile(0.995) + z80) ** 2 / base - 1
    r04 = (norm_quantile(0.98) + z80) ** 2 / base - 1
    print(f"[info] Wiens p. 213 efficiency remark: two-sided normal approximation gives +{r01*100:.1f}% (alpha 0.01) and +{r04*100:.1f}% (alpha 0.04); printed 48% and 6%")

    # ---- Marcus, Peritz and Gabriel Table 3 (printed p. 659) ----
    xbar = [8, 10, 16, 12, 8, 8]
    table3 = {
        ((1, 2, 3, 4, 5, 6),): F(22, 3),
        ((1,), (2, 3, 4, 5, 6)): F(4, 5),
        ((1, 2), (3, 4, 5, 6)): F(2),
        ((1, 2, 3), (4, 5, 6)): F(104, 3),
        ((1, 2, 3, 4), (5, 6)): F(27),
        ((1, 2, 3, 4, 5), (6,)): F(64, 5),
        ((1, 2, 3), (4,), (5, 6)): F(104, 3),
        ((1, 2, 3), (4, 5), (6,)): F(104, 3),
        ((1, 2, 3, 4), (5,), (6,)): F(27),
        ((1, 2, 3), (4,), (5,), (6,)): F(104, 3),
    }
    ok = all(d2_statistic(xbar, g) == v for g, v in table3.items())
    check("Marcus Table 3: all ten D_g^2 statistics (7.333, 0.800, 2.000, 34.667, 27.000, 12.800, ...)", ok)
    fit = pava(xbar)
    check("Marcus Table 2: amalgamated estimates for (1..6) are (8, 10, 11, 11, 11, 11)", fit == [8, 10, 11, 11, 11, 11])

    # ---- Marcus Table 1 and single-block critical values (printed pp. 658-659) ----
    table1 = {
        (2, 2): (4.231, 7.290), (2, 3): (5.088, 8.352), (2, 4): (5.686, 9.090), (2, 5): (6.144, 9.653),
        (2, 6): (6.513, 10.106), (2, 7): (6.822, 10.484), (2, 8): (7.087, 10.808), (3, 3): (5.862, 9.295),
        (3, 4): (6.415, 9.970), (3, 5): (6.845, 10.494), (3, 6): (7.194, 10.919), (3, 7): (7.488, 11.277),
        (4, 4): (6.944, 10.611), (4, 5): (7.356, 11.110), (4, 6): (7.694, 11.518), (5, 5): (7.757, 11.593),
        (2, 2, 2): (5.435, 8.747), (2, 2, 3): (6.184, 9.661), (2, 2, 4): (6.723, 10.320), (2, 2, 5): (7.144, 10.832),
        (2, 2, 6): (7.487, 11.250), (2, 3, 3): (6.885, 10.508), (2, 3, 4): (7.394, 11.128), (2, 3, 5): (7.799, 11.613),
        (2, 4, 4): (7.892, 11.723), (3, 3, 3): (7.552, 11.307), (3, 3, 4): (8.043, 11.897),
        (2, 2, 2, 2): (6.322, 10.019), (2, 2, 2, 3): (6.966, 10.848), (2, 2, 2, 4): (7.440, 11.457),
        (2, 2, 3, 3): (7.585, 11.633), (2, 2, 2, 2, 2): (7.248, 11.001),
    }
    discrepancies = {}
    print("[info] Marcus Table 1 recomputation (equal n, sigma^2 = 1); printed vs computed, 5% and 1% points")
    for lams, (c5, c1) in table1.items():
        g5 = dg2_critical(lams, 0.05)
        g1 = dg2_critical(lams, 0.01)
        flag5 = abs(g5 - c5) > 0.001
        flag1 = abs(g1 - c1) > 0.001
        print(f"       {str(lams):16s} 5%: {c5:7.3f} / {g5:7.4f}   1%: {c1:7.3f} / {g1:7.4f}" + ("   <-- differs" if flag5 or flag1 else ""))
        if flag5 or flag1:
            discrepancies[lams] = (round(g5, 3) if flag5 else None, round(g1, 3) if flag1 else None)
    expected_discrepancies = {
        (2, 3, 4): (7.397, None),
        (2, 2, 2, 2): (6.498, None),
        (2, 2, 2, 3): (7.185, None),
        (2, 2, 2, 4): (7.688, None),
        (2, 2, 3, 3): (7.840, None),
        (2, 2, 2, 2, 2): (7.480, 11.183),
    }
    check("Marcus Table 1: 58 of 64 printed points agree with the p. 658 formula to within 0.001", len(discrepancies) == 6 and all(len(v) == 2 for v in discrepancies.values()))
    check("Marcus Table 1: the six differing rows are (2,3,4) at 5% and every row with four or five blocks at 5% (plus (2,2,2,2,2) at 1%)", discrepancies == expected_discrepancies, f"{discrepancies}")
    check("Marcus Table 1: printed (2,2,2,2) 5% point 6.322 has upper-tail probability about 0.054, not 0.05", abs(dg2_sf((2, 2, 2, 2), 6.322) - 0.0542) < 0.0005, f"{dg2_sf((2, 2, 2, 2), 6.322):.4f}")
    single = {(3,): 3.820, (4,): 4.528, (5,): 5.049, (6,): 5.460}
    for lams, exp in single.items():
        got = dg2_critical(lams, 0.05)
        check(f"Marcus Table 3 single-block 5% point for k={lams[0]}: {exp} (not in Table 1; Bartholomew chi-bar-square point)", abs(got - exp) < 0.001, f"computed {got:.4f}")
    # singleton blocks contribute nothing (printed p. 658)
    check("Marcus: singleton blocks do not change the null distribution ((1),(2,3,4,5,6) uses the k=5 point)", abs(dg2_critical((1, 5), 0.05) - dg2_critical((5,), 0.05)) < 1e-9)

    # ---- Marcus closed-testing argument, finite check: A subset of B on an enumerated family ----
    # Family: all subsets P of {1,2,3} (omega_P: mu_i = mu_0 for i in P), true set T = {1,2}.
    # Rejecting any true omega_P requires every omega_R with R superset of P to be rejected, in particular omega_T' with T' = union of true P's = T.
    true_sets = [frozenset(s) for s in [(1,), (2,), (1, 2)]]
    T = frozenset({1, 2})
    ok = all(T >= P for P in true_sets)
    check("Marcus p. 656: the intersection of all true hypotheses (P = T) is implied by every true hypothesis in a closed family", ok)

    print()
    if FAILURES:
        print(f"{len(FAILURES)} check(s) failed:")
        for f_ in FAILURES:
            print("  -", f_)
        return 1
    print("all checks passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
