/**
 * Per-quantity deviation aggregation for discussion item S1 (Batch 2
 * addendum U8). Reads the regenerated oracle matrices (Phase 1, Phase 2A,
 * tail corpus) and writes, for every quantity in every corpus, the maximum
 * and 95th-percentile relative difference across that corpus's datasets.
 *
 * The percentile is the nearest-rank method (ceil(0.95 * n)-th smallest) -
 * a mechanical choice documented here because the corpora are small (4-7
 * datasets each); with n <= 20 the nearest-rank p95 equals the maximum,
 * which the table makes visible rather than hiding.
 *
 * This aggregation DECIDES NOTHING: no tolerance value is chosen here.
 * Choosing one is discussion item S1. See S1-BRIEF.md in the output
 * directory for the decision scope.
 *
 * Usage: tsx tooling/src/evidence/oracle-deviation-summary.ts
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { repoRoot } from "../lib/repo.js";
import { compareCorpus } from "./oracle-comparisons.js";

interface QuantityStats {
  quantity: string;
  n_datasets: number;
  max_rel_diff: number;
  p95_rel_diff: number;
  max_dataset: string;
}

function nearestRankP95(sortedAscending: number[]): number {
  const rank = Math.ceil(0.95 * sortedAscending.length);
  return sortedAscending[Math.max(0, rank - 1)] as number;
}

const corpora = (["phase1", "phase2a", "tail", "floor"] as const).map((c) => compareCorpus(c));

const summary: Record<string, QuantityStats[]> = {};
for (const corpus of corpora) {
  const byQuantity = new Map<string, Array<{ dataset: string; relDiff: number }>>();
  for (const [datasetName, dataset] of Object.entries(corpus.datasets)) {
    for (const [quantity, comparison] of Object.entries(dataset.comparisons)) {
      const list = byQuantity.get(quantity) ?? [];
      list.push({ dataset: datasetName, relDiff: comparison.rel_diff });
      byQuantity.set(quantity, list);
    }
  }
  summary[corpus.corpus] = [...byQuantity.entries()].map(([quantity, values]) => {
    const sorted = values.map((v) => v.relDiff).sort((a, b) => a - b);
    const maxEntry = values.reduce((best, v) => (v.relDiff > best.relDiff ? v : best));
    return {
      quantity,
      n_datasets: values.length,
      max_rel_diff: maxEntry.relDiff,
      p95_rel_diff: nearestRankP95(sorted),
      max_dataset: maxEntry.dataset,
    };
  });
}

const outDir = path.join(repoRoot, "evidence", "development", "oracle-deviation-summary");
fs.mkdirSync(outDir, { recursive: true });

const jsonDoc = {
  schema: "nrs-oracle-deviation-summary",
  schema_version: "0.1.0",
  description:
    "Per-quantity max/p95 relative differences of the reference kernel vs captured SciPy/mpmath oracle values, aggregated per corpus. Input for discussion item S1; no tolerance is decided here. Not R1-08 evidence (that gate closed on a separate disjoint-lineage oracle).",
  percentile_method: "nearest-rank (ceil(0.95*n)); equals the maximum for these small corpora",
  generated_by: "tooling/src/evidence/oracle-deviation-summary.ts",
  corpora: summary,
};
fs.writeFileSync(
  path.join(outDir, "summary.json"),
  `${JSON.stringify(jsonDoc, null, 2)}\n`,
  "utf8",
);

const lines: string[] = [
  "# Oracle Deviation Summary (S1 input)",
  "",
  "Generated by `tooling/src/evidence/oracle-deviation-summary.ts` from the",
  "regenerated oracle matrices. Per quantity: max and nearest-rank p95 of the",
  "relative difference between the live reference kernel and the captured",
  "SciPy/mpmath oracle values. **No tolerance is decided here - that is",
  "discussion item S1** (see [S1-BRIEF.md](S1-BRIEF.md)). With 4-7 datasets",
  "per corpus, nearest-rank p95 equals the maximum; the column exists so the",
  "table's shape survives future corpus growth without a format change.",
  "",
];
for (const corpus of corpora) {
  lines.push(`## Corpus: ${corpus.corpus}`, "");
  lines.push("| Quantity | n | max rel_diff | p95 rel_diff | max at dataset |");
  lines.push("| --- | --- | --- | --- | --- |");
  for (const stat of summary[corpus.corpus] ?? []) {
    lines.push(
      `| ${stat.quantity} | ${stat.n_datasets} | ${stat.max_rel_diff.toExponential(3)} | ${stat.p95_rel_diff.toExponential(3)} | ${stat.max_dataset} |`,
    );
  }
  lines.push("");
}
// Drop the final per-corpus spacer so the file does not end with two blank
// lines (markdownlint MD012).
if (lines[lines.length - 1] === "") lines.pop();
fs.writeFileSync(path.join(outDir, "summary.md"), `${lines.join("\n")}\n`, "utf8");

console.log(
  `oracle-deviation-summary: wrote evidence/development/oracle-deviation-summary/{summary.json,summary.md}`,
);
