"""Build the review inventory from an explicit repository path and this archive."""
import hashlib,json,subprocess,sys
from pathlib import Path
root=Path(sys.argv[1]).resolve(); out=Path(__file__).resolve().parent
initial='e2c998124078b737d5e0776a7fc0c2094b51fa36'; final='dc6c9694d6a5221dfed0ea5bf4af55246549cd68'
def git(*args): return subprocess.check_output(['git',*args],cwd=root)
def row(path,commit):
 b=git('show',commit+':'+path)
 return {'path':path,'commit':commit,'git_blob':git('rev-parse',commit+':'+path).decode().strip(),'sha256':hashlib.sha256(b).hexdigest(),'bytes':len(b)}
changed=git('diff','--name-only',initial+'^',final).decode().splitlines()
selected=['AGENTS.md','CHARTER.md','AUTHORITY.md','authority/authority-manifest.yaml','registries/requirements.yaml','governance/ID-POLICY.md','governance/RFC.md','.prettierrc.json','review-inputs/r3-execution-control-review-539f848/REVIEW.md','review-inputs/r3-execution-control-review-539f848/INPUTS.json','governance/drafts/release-3-preparation/holm-execution-investigation-20260911/SOURCE-REVIEW.md','governance/drafts/release-3-preparation/holm-envelope-experiment-20260911/envelope.mjs','governance/drafts/release-3-preparation/holm-declaration-binding-experiment-20260911/bridge.mjs']
files=[row(p,final) for p in sorted(set(changed+selected))]
files.extend(row(p,initial) for p in changed)
artifacts=[]
for f in sorted(out.iterdir()):
 if f.is_file() and f.name not in ['INPUTS.json','SHA256SUMS.txt']:
  b=f.read_bytes(); artifacts.append({'path':f.name,'sha256':hashlib.sha256(b).hexdigest(),'bytes':len(b)})
v={'kind':'independent-controlled-execution-review-inputs','date':'2026-09-11','initial_candidate':initial,'initial_parent':git('rev-parse',initial+'^').decode().strip(),'initial_tree':git('rev-parse',initial+'^{tree}').decode().strip(),'final_candidate':final,'final_parent':git('rev-parse',final+'^').decode().strip(),'final_tree':git('rev-parse',final+'^{tree}').decode().strip(),'verdict':'PASS within documented unissued research and trusted-program scope','independence':{'reviewer':'OpenAI Codex /root/r3_controlled_review','separate_agent_context':True,'same_inherited_model_configuration':True,'shared_execution_infrastructure':True,'human_review':False,'subagents_started':False,'private_repository_access':False,'implementation_authorship':False},'tests':{'rootless_initial':{'passed':5,'controls':13},'rootless_final':{'passed':13,'controls':13},'independent_entry_initial_unchanged_final':{'passed':16,'controls':16},'author_local_final_rerun':{'passed':7,'controls':7},'local_kernel_cgroup_tests':'NOT_RUN; read-only mount; state-machine files are ordinary temporary files'},'received_ci':{'initial_run':34599267610,'initial_candidate':initial,'initial_controls':20,'initial_passed':20,'final_run':34599836146,'final_candidate':final,'final_artifact':10263403165,'final_zip_sha256_coordinator_verified':'22ca0509b22527024ee19b5cf43724f5ad9ec9a4a4cdfb5913f98d640412c339','final_controls':32,'final_passed':32,'provenance':'Author-run dedicated CI; exact extracted receipts inspected, not independently run kernel experiments'},'primary_source_reuse':{'archived_inventory':'review-inputs/r3-execution-control-review-539f848/INPUTS.json','scope':'Reuse prior PR316 Linux/Node/Python basis; no new numerical methodology choice','live_corroboration':[{'url':'https://docs.kernel.org/admin-guide/cgroup-v2.html','date':'2026-09-11','scope':'Distribution layout, kill, group OOM, counters and live population'},{'url':'https://man7.org/linux/man-pages/man2/PR_SET_CHILD_SUBREAPER.2const.html','date':'2026-09-11','scope':'Orphan adoption and waitability'},{'url':'https://docs.python.org/3.12/library/subprocess.html','date':'2026-09-11','scope':'close_fds behavior'}],'live_source_hashes':'Not captured; these corroborate but do not replace prior hashed source snapshots'},'repository_inputs':files,'review_artifacts':artifacts}
(out/'INPUTS.json').write_text(json.dumps(v,indent=2)+'\n')
