// Generate a local informative view; never modify registered/generated authority.
import fs from "node:fs";
import assert from "node:assert/strict";
const read = (n) => JSON.parse(fs.readFileSync(new URL(n, import.meta.url), "utf8"));
const ids = read("./identities.json");
const outcomes = read("./outcomes.json");
const diag = read("./diagnostics.json");
const record = read("./record.schema.json");
const report = read("./report.schema.json");
const allIds = [
  ...Object.entries(ids).filter(([k]) => k !== "checks"),
  ...Object.entries(ids.checks).map(([k, v]) => ["check: " + k, v]),
];
assert.equal(new Set(allIds.map((x) => x[1])).size, allIds.length);
for (const [, id] of allIds)
  assert.match(id, /^https:\/\/nomue\.ai\/id\/[a-z]+\/[a-z]+(?:-[a-z]+)*\/0\.3\.0-candidate\.1$/);
assert.equal(record.properties.payload.properties.contract_id.const, ids.contract);
assert.equal(record.properties.interpretation_bundle_id.const, ids.bundle);
assert.equal(record.properties.profile_id.const, ids.profile);
for (const [i, stage] of Object.keys(ids.checks).entries())
  assert.equal(
    report.properties.checks.prefixItems[i].allOf[1].properties.check_ref.const,
    ids.checks[stage],
  );
const bundle = read("./bundle.json");
assert.deepEqual(bundle.bindings, ids);
const policy = read("./check-policy.json");
assert.equal(policy.check_id, ids.checks.arithmetic);
assert.equal(policy.exact_numerator_tolerance, 0);
assert.equal(policy.display_bits_tolerance, 0);
let text =
  "# Candidate identity and outcome index\n\nGenerated by index.mjs. Informative, unissued proposed allocations only.\n\n";
text += "## Proposed identities\n\n| Role | Proposed identifier |\n| --- | --- |\n";
for (const [role, id] of allIds) text += `| ${role} | \`${id}\` |\n`;
text +=
  "\n## Check-owned numerical policy\n\nExact denominator: 2^1074. Exact numerator tolerance: 0. Display bit-pattern\ntolerance: 0. Projection: nearest binary64, ties to even. No alpha input.\n\n";
text +=
  "## Execution refusal precedence\n\nThe first observed cause wins; all observed causes remain in the private receipt.\n\n| Cause | Refusal kind | Proposed reason | Limit category |\n| --- | --- | --- | --- |\n";
for (const category of outcomes.execution_precedence) {
  const r = outcomes.execution[category];
  text += `| ${category} | ${r.refusal_kind} | ${outcomes.reasons[r.reason]} | ${r.limit_category ?? "absent"} |\n`;
}
text +=
  "\n## Input refusal mapping\n\n| Private reason | Stage | Refusal kind | Proposed reason | Limit category |\n| --- | --- | --- | --- | --- |\n";
for (const [reason, r] of Object.entries(diag.refusals))
  text += `| ${reason} | ${r.stage} | ${r.refusal_kind} | ${outcomes.reasons[reason]} | ${outcomes.input_limits[reason] ?? "absent"} |\n`;
text += "\n## Scoped check reasons\n\n| Check | Proposed reason codes |\n| --- | --- |\n";
for (const [stage, reasons] of Object.entries(diag.checks))
  text += `| ${stage} | ${reasons.map((r) => outcomes.reasons[r]).join(", ")} |\n`;
text += `\nA gated check uses ${outcomes.reasons.prerequisite_failed}. No check carries an overall Record verdict.\n`;
// Use the repository formatter so --check compares final committed bytes.
const { format } = await import("prettier");
text = await format(text, { filepath: "CANDIDATE-INDEX.md", proseWrap: "preserve" });
const target = new URL("./CANDIDATE-INDEX.md", import.meta.url);
if (process.argv.includes("--check")) assert.equal(fs.readFileSync(target, "utf8"), text);
else fs.writeFileSync(target, text);
console.log("Candidate index and exact bindings checked");
